### ISSUE TITLE
entities: Improve & bugfix

### ISSUE THREAD

**Issue by geaaru** [mocaccinoOS/mocaccino#19]
entities specs to add users to existing groups are now broken.

https://github.com/mudler/entities/pull/7

https://github.com/mudler/entities/pull/6

These pull requests must be merged ASAP.

Error trace related to PR7:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x567207]goroutine 1 [running]:
github.com/mudler/entities/pkg/entities.Group.Apply(0xc000014be8, 0x5, 0x0, 0x0, 0x0, 0xc000014c00, 0x3, 0x7ffd0cbf27cf, 0xa, 0x67ee01, ...)
	/home/geaaru/go/src/github.com/mudler/entities/pkg/entities/group.go:270 +0x5c7
github.com/mudler/entities/cmd.glob..func1(0x7ea720, 0xc00001e500, 0x1, 0x4, 0x0, 0x0)
	/home/geaaru/go/src/github.com/mudler/entities/cmd/apply.go:37 +0xe4
github.com/spf13/cobra.(*Command).execute(0x7ea720, 0xc00001e4c0, 0x4, 0x4, 0x7ea720, 0xc00001e4c0)
	/home/geaaru/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x7ea480, 0x444aca, 0x7d17c0, 0xc000038778)
	/home/geaaru/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	/home/geaaru/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/mudler/entities/cmd.Execute()
	/home/geaaru/go/src/github.com/mudler/entities/cmd/root.go:45 +0x31
main.main()
	/home/geaaru/go/src/github.com/mudler/entities/main.go:21 +0x25
```

**Comment by geaaru** [comment]
entities is 0.5.2 is been released.

https://github.com/mudler/entities/releases/tag/0.5.2
